<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="WorkerSuite" duration-ms="134864" started-at="2018-08-06T09:09:20Z" finished-at="2018-08-06T09:11:35Z">
    <groups>
    </groups>
    <test name="WorkerTest" duration-ms="134864" started-at="2018-08-06T09:09:20Z" finished-at="2018-08-06T09:11:35Z">
      <class name="cn.lixing.worker.Test.TestCase.BindCodeTesCase">
        <test-method status="PASS" signature="initTestData()[pri:0, instance:cn.lixing.worker.Test.TestCase.BindCodeTesCase@4157f54e]" name="initTestData" is-config="true" duration-ms="27115" started-at="2018-08-06T17:09:20Z" finished-at="2018-08-06T17:09:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTestData -->
        <test-method status="FAIL" signature="BindCodeTest_01(java.lang.String)[pri:0, instance:cn.lixing.worker.Test.TestCase.BindCodeTesCase@4157f54e]" name="BindCodeTest_01" duration-ms="38673" started-at="2018-08-06T17:09:47Z" data-provider="BindCodeData" finished-at="2018-08-06T17:10:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[9pqIHdPQS]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [607270598]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [607270598]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at cn.lixing.worker.Test.TestCase.BindCodeTesCase.BindCodeTest_01(BindCodeTesCase.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BindCodeTest_01 -->
        <test-method status="PASS" signature="close()[pri:0, instance:cn.lixing.worker.Test.TestCase.BindCodeTesCase@4157f54e]" name="close" is-config="true" duration-ms="1021" started-at="2018-08-06T17:10:26Z" finished-at="2018-08-06T17:10:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- cn.lixing.worker.Test.TestCase.BindCodeTesCase -->
      <class name="cn.lixing.worker.Test.TestCase.RepCodeTestCase">
        <test-method status="PASS" signature="BeforeClass()[pri:0, instance:cn.lixing.worker.Test.TestCase.RepCodeTestCase@90f6bfd]" name="BeforeClass" is-config="true" duration-ms="14072" started-at="2018-08-06T17:10:27Z" finished-at="2018-08-06T17:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeClass -->
        <test-method status="FAIL" signature="RepCodeTestCase_01(java.lang.String, java.lang.String)[pri:0, instance:cn.lixing.worker.Test.TestCase.RepCodeTestCase@90f6bfd]" name="RepCodeTestCase_01" duration-ms="8679" started-at="2018-08-06T17:10:41Z" data-provider="repcodeDatas" finished-at="2018-08-06T17:10:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[9pqIHdPQS]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[44CBA241D7]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at cn.lixing.worker.Test.page.WorkerPage.click(WorkerPage.java:36)
	at cn.lixing.worker.Test.repcode.page.RepQrCodePage.reqDevicePage(RepQrCodePage.java:40)
	at cn.lixing.worker.Test.TestCase.RepCodeTestCase.RepCodeTestCase_01(RepCodeTestCase.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RepCodeTestCase_01 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:cn.lixing.worker.Test.TestCase.RepCodeTestCase@90f6bfd]" name="afterClass" is-config="true" duration-ms="863" started-at="2018-08-06T17:10:50Z" finished-at="2018-08-06T17:10:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- cn.lixing.worker.Test.TestCase.RepCodeTestCase -->
      <class name="cn.lixing.worker.Test.TestCase.DeCodeTestCase">
        <test-method status="PASS" signature="initTestClass()[pri:0, instance:cn.lixing.worker.Test.TestCase.DeCodeTestCase@47f6473]" name="initTestClass" is-config="true" duration-ms="8091" started-at="2018-08-06T17:10:51Z" finished-at="2018-08-06T17:10:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTestClass -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:cn.lixing.worker.Test.TestCase.DeCodeTestCase@47f6473]" name="BeforeMethod" is-config="true" duration-ms="6132" started-at="2018-08-06T17:10:59Z" finished-at="2018-08-06T17:11:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="useDeQrCodeTestCase(java.lang.String)[pri:0, instance:cn.lixing.worker.Test.TestCase.DeCodeTestCase@47f6473]" name="useDeQrCodeTestCase" duration-ms="28685" started-at="2018-08-06T17:11:05Z" data-provider="decodeData" finished-at="2018-08-06T17:11:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ebBnzEbQS]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[chrome not reachable
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4.07 seconds
Build info: version: 'unknown', revision: '86a5d70', time: '2017-02-16 07:47:51 -0800'
System info: host: 'ADMIN-PC', ip: '192.168.163.177', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_51'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9), userDataDir=C:\Users\admin\AppData\Local\Temp\scoped_dir9220_18868}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=56.0.2924.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 3d731a26490f91450723a6e3a3c7a649
*** Element info: {Using=xpath, value=.//*[@id='routertransition']/div[5]/div}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: chrome not reachable
  (Session info: chrome=56.0.2924.87)
  (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4.07 seconds
Build info: version: 'unknown', revision: '86a5d70', time: '2017-02-16 07:47:51 -0800'
System info: host: 'ADMIN-PC', ip: '192.168.163.177', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_51'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9), userDataDir=C:\Users\admin\AppData\Local\Temp\scoped_dir9220_18868}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=56.0.2924.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 3d731a26490f91450723a6e3a3c7a649
*** Element info: {Using=xpath, value=.//*[@id='routertransition']/div[5]/div}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:473)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:360)
	at cn.lixing.worker.Test.page.WorkerPage.getWebElement(WorkerPage.java:31)
	at cn.lixing.worker.Test.decode.page.DeQrCodeElementObject.getDECODEDEVICEBNTElement(DeQrCodeElementObject.java:75)
	at cn.lixing.worker.Test.decode.page.DeQrCodePage.useDeQrCodePage(DeQrCodePage.java:47)
	at cn.lixing.worker.Test.TestCase.DeCodeTestCase.useDeQrCodeTestCase(DeCodeTestCase.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- useDeQrCodeTestCase -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:cn.lixing.worker.Test.TestCase.DeCodeTestCase@47f6473]" name="afterClass" is-config="true" duration-ms="1512" started-at="2018-08-06T17:11:34Z" finished-at="2018-08-06T17:11:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- cn.lixing.worker.Test.TestCase.DeCodeTestCase -->
    </test> <!-- WorkerTest -->
  </suite> <!-- WorkerSuite -->
</testng-results>
